In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier


In [3]:
dataset = pd.read_csv('archive.zip')

In [4]:
dataset.head()

Unnamed: 0 India GDP - Historical Data India GDP - Historical Data.1  \
0         NaN                        Year            GDP in (Billion) $   
1         0.0                        2021                        3173.4   
2         1.0                        2020                       2667.69   
3         2.0                        2019                       2831.55   
4         3.0                        2018                       2702.93   

  India GDP - Historical Data.2 India GDP - Historical Data.3  
0          Per Capita in rupees                      Growth %  
1                        182160                          8.95  
2                        154640                          -6.6  
3                        165760                          3.74  
4                        159840                          6.45

In [5]:
dataset.isnull().sum()

Unnamed: 0                       1
India GDP - Historical Data      0
India GDP - Historical Data.1    0
India GDP - Historical Data.2    0
India GDP - Historical Data.3    0
dtype: int64

In [6]:
dataset.drop('Unnamed: 0',axis=1,inplace=True)

In [7]:
dataset.columns = dataset.iloc[0]

dataset = dataset.iloc[1:].reset_index(drop=True)

dataset.head()

0  Year GDP in (Billion) $ Per Capita in rupees Growth %
0  2021             3173.4               182160     8.95
1  2020            2667.69               154640     -6.6
2  2019            2831.55               165760     3.74
3  2018            2702.93               159840     6.45
4  2017            2651.47               158480      6.8

In [8]:
dataset['Growth %'].unique()

array(['8.95', '-6.6', '3.74', '6.45', '6.8', '8.26', '8', '7.41', '6.39',
       '5.46', '5.24', '8.5', '7.86', '3.09', '7.66', '8.06', '7.92',
       '3.8', '4.82', '3.84', '8.85', '6.18', '4.05', '7.55', '7.57',
       '6.66', '4.75', '5.48', '1.06', '5.53', '5.95', '9.63', '3.97',
       '4.78', '5.25', '3.82', '7.29', '3.48', '6.01', '6.74', '-5.24',
       '5.71', '7.25', '1.66', '9.15', '1.19', '3.3', '-0.55', '1.64',
       '5.16', '6.54', '3.39', '7.83', '-0.06', '-2.64', '7.45', '5.99',
       '2.93', '3.72', '0'], dtype=object)

In [9]:
dataset['Growth %'].max()

'9.63'

In [72]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Year                  62 non-null     int32 
 1   GDP in (Billion) $    62 non-null     object
 2   Per Capita in rupees  62 non-null     object
 3   Growth %              62 non-null     object
dtypes: int32(1), object(3)
memory usage: 1.8+ KB


In [15]:
y = dataset['GDP in (Billion) $']
X = dataset[['Year','Per Capita in rupees','Growth %']]

In [16]:
y.shape


(62,)

In [17]:
X.shape

(62, 3)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
X_train.shape

(41, 3)

In [20]:
X_test.shape

(21, 3)

In [22]:
y_train.shape

(41,)

In [23]:
y_test.shape

(21,)

#   Linear Regression

In [57]:
from sklearn.tree import DecisionTreeRegressor, export_graphviz
from sklearn import tree
from IPython.display import SVG
from graphviz import Source
from IPython.display import display

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [26]:
regressor.coef_

array([-2.37073593,  0.01822789, -4.81037938])

In [27]:
regressor.intercept_

4561.643348019076

In [28]:
y_pred = regressor.predict(X_train)
y_pred

array([ 353.90650484, 2635.91422062,  103.85913787,  483.97743357,
         19.69338956,  262.11445134,   25.55097172,  224.51196374,
         26.35589606,  943.967924  ,  230.02749806,  306.9067482 ,
        340.98903789,  412.96757664,  111.05415876, 1735.85375059,
        322.17579718,   32.30594141,  145.25602912,  243.65763884,
        275.03576575,   65.82543894, 2623.26600362,  447.69601939,
       2778.59153995,   68.56023812,  245.65994638,  282.41982916,
        397.43427043,   18.68523147, 1894.98796164,  424.50852352,
        572.90212112,   34.57588538,  453.73519159, 2046.59203845,
        221.80710724, 1265.79041337,  252.84490914,   29.79390159,
        249.75159375])

In [29]:
y_pred = regressor.predict(X_test)

In [30]:
y_pred

array([5.45633188e+01, 8.93761581e+01, 3.04772537e+03, 3.88354728e+01,
       2.26962049e+03, 7.82923947e+01, 8.12854852e+02, 1.36799597e+03,
       3.76628518e+02, 2.74058508e+01, 2.78253143e+02, 1.87114371e+03,
       1.13777950e+02, 1.24311441e+03, 3.18510186e+02, 3.27692434e+02,
       2.66001705e+03, 6.88359482e+02, 7.30698791e-01, 1.87304870e+03,
       2.08804657e+03])

In [36]:
mean_squared_error(y_pred,y_test)

1488.237820790752

In [39]:
#math.sqrt(mean_squared_error(y_train, y_pred))

In [40]:
math.sqrt(mean_squared_error(y_test, y_pred))

38.57768552921173

In [41]:
r2_score(y_test, y_pred)

0.998449798407232

#  Ridge & Lasso Regression

In [43]:
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.linear_model import Lasso, LassoCV

In [45]:
alphas = 10 ** np.arange(1, 5)
print('different alpha values:', alphas)

# stores the weights of each feature
ridge_weight = []
for alpha in alphas:    
    ridge = Ridge(alpha = alpha, fit_intercept = True)
    ridge.fit(X_train, y_train)
    ridge_weight.append(ridge.coef_)


different alpha values: [   10   100  1000 10000]


In [46]:
ridge_weight

[array([-2.37657895,  0.01822986, -4.70128308]),
 array([-2.40467144,  0.01823958, -3.91468356]),
 array([-2.10998711,  0.0181483 , -1.56733441]),
 array([-0.71301441,  0.01770558, -0.26996062])]

In [53]:
ridge.intercept_

1264.1542451813366

In [56]:
ridge.coef_

array([-0.71301441,  0.01770558, -0.26996062])

In [59]:
alphas = 10 ** np.arange(1, 5)
print('different alpha values:', alphas)

# stores the weights of each feature
lasso_weight = []
for alpha in alphas:    
    lasso = Lasso(alpha = alpha, fit_intercept = True)
    lasso.fit(X_train, y_train)
    lasso_weight.append(lasso.coef_)


different alpha values: [   10   100  1000 10000]


In [60]:
lasso.intercept_

-145.80927869905588

In [61]:
lasso.coef_

array([-0.        ,  0.01747395, -0.        ])

In [62]:
def generate_random_data(size, seed):
    """Example of collinear features existing within the data"""
    rstate = np.random.RandomState(seed)
    X_seed = rstate.normal(0, 1, size)
    X1 = X_seed + rstate.normal(0, .1, size)
    X2 = X_seed + rstate.normal(0, .1, size)
    X3 = X_seed + rstate.normal(0, .1, size)
    y = X1 + X2 + X3 + rstate.normal(0, 1, size)
    X = np.array([X1, X2, X3]).T
    return X, y


def pretty_print_linear(estimator, names = None, sort = False):
    """A helper method for pretty-printing linear models' coefficients"""
    coef = estimator.coef_
    if names is None:
        names = ['X%s' % x for x in range(1, len(coef) + 1)]

    info = zip(coef, names)
    if sort:
        info = sorted(info, key = lambda x: -np.abs(x[0]))
    
    output = ['{} * {}'.format(round(coef, 3), name) for coef, name in info]
    output = ' + '.join(output)
    return output

In [63]:
size = 100
for seed in range(10):
    print('Random seed:', seed)
    X, y = generate_random_data(size, seed)
 
    lasso = Lasso()
    lasso.fit(X, y)
    print('Lasso model:', pretty_print_linear(lasso))
 
    ridge = Ridge(alpha = 10)
    ridge.fit(X, y)
    print('Ridge model:', pretty_print_linear(ridge))
    print()


Random seed: 0
Lasso model: 0.486 * X1 + 1.508 * X2 + 0.0 * X3
Ridge model: 0.938 * X1 + 1.059 * X2 + 0.877 * X3

Random seed: 1
Lasso model: 1.034 * X1 + 0.626 * X2 + 0.0 * X3
Ridge model: 0.984 * X1 + 1.068 * X2 + 0.759 * X3

Random seed: 2
Lasso model: 1.361 * X1 + 0.0 * X2 + 0.782 * X3
Ridge model: 0.972 * X1 + 0.943 * X2 + 1.085 * X3

Random seed: 3
Lasso model: 0.0 * X1 + 1.008 * X2 + 1.134 * X3
Ridge model: 0.919 * X1 + 1.005 * X2 + 1.033 * X3

Random seed: 4
Lasso model: 0.27 * X1 + 0.0 * X2 + 1.832 * X3
Ridge model: 0.964 * X1 + 0.982 * X2 + 1.098 * X3

Random seed: 5
Lasso model: 0.0 * X1 + 0.035 * X2 + 1.854 * X3
Ridge model: 0.758 * X1 + 1.011 * X2 + 1.139 * X3

Random seed: 6
Lasso model: 0.486 * X1 + 0.0 * X2 + 1.601 * X3
Ridge model: 1.016 * X1 + 0.89 * X2 + 1.091 * X3

Random seed: 7
Lasso model: 0.441 * X1 + 0.036 * X2 + 1.582 * X3
Ridge model: 1.018 * X1 + 1.039 * X2 + 0.901 * X3

Random seed: 8
Lasso model: 0.28 * X1 + 1.974 * X2 + 0.0 * X3
Ridge model: 0.907 * X1 + 

# THE  END